### PR TITLE
shellsheck path fix

### PR DESCRIPTION
**Pull request by assisjrt**
fix error: ~/.asdf/plugins/gcloud/bin/exec-env: line 6: ~/.asdf/bin/../lib/utils.bash: No file or directory

### CODE REVIEW

**Comment by esselius** [comment]
👍

**Comment by jthegedus** [comment]
Hi @assisjrt @esselius 

Can either of you elaborate on the need for this change? The file is suffixed with `.bash` and the test now errors as it cannot find a `.sh` file:

```shell
# GitHub Actions error
  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/asdf.XXXX.aHNgZB3N/plugins/gcloud/bin/exec-env: line 6: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/asdf.XXXX.aHNgZB3N/bin/../lib/utils.sh: No such file or directory
```

If this errors for you, then it should error in many other places (all `bin/` commands) as the same code is used elsewhere.

Can you provide more details about your machine's setup?

**Comment by esselius** [comment]
Screenshot 2020-09-02 at 07 45 17

My asdf version ~~is~~ was `v0.7.6-6207e42` on macos 10.15.6, seems like the file extension was changed in 0.7.7, sorry to bother you 😬

**Comment by jthegedus** [comment]
All good. We'll be addressing the UX of plugins updates etc soon in the core of `asdf`. I'll close the issue assuming the update fixed your issue, if it did not, feel free to re-open

**Pull request closed without merging**
