### PR TITLE
fix: check for both python3 and python in exec-env

### PR DESCRIPTION
**Pull request by adamfeldman**
This fix enables the use of Homebrew-installed Python with this plugin. 

See also 9d7ff92 for an earlier commit that adjusted `python` --> `python3`.

## Description

Changes `bin/exec-env` to check for `python3` instead of `python`.

## Motivation and Context

Not working, on macOS with Homebrew-installed Python:

➜  ~ gcloud --version
🚨  Python not found and is required for gcloud. Might I suggest https://github.com/danhper/asdf-python
➜  ~ command -v python
➜  ~ 
➜ ~ command -v python3
/opt/homebrew/bin/python3

An alias doesn't fix it either:

➜  ~ command -v python 
alias python=python3
➜ ~ command -v python3
/opt/homebrew/bin/python3
➜  ~ gcloud help     
🚨  Python not found and is required for gcloud. Might I suggest https://github.com/danhper/asdf-python
➜  ~ which python
python: aliased to python3
➜  ~ which python3
/opt/homebrew/bin/python3

After applying the change, it works:

➜  ~ gcloud --version
Google Cloud SDK 433.0.0
bq 2.0.93
core 2023.05.26
gcloud-crc32c 1.0.0
gsutil 5.24

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by jthegedus** [comment]
Thanks for the PR @adamfeldman 

I made a change so that it prefers `python3` but if it is not found falls back to `python`.

**Comment by adamfeldman** [comment]
Awesome, thank you @jthegedus!

**Comment by jthegedus** [comment]
Sorry for the delay :sweat_smile:

**Comment by adamfeldman** [comment]
You were plenty quick! Thank you for maintaining this! 😄 🚀

**Pull request merged**
